exercises/practice/hello-world/.meta/proof.ci.wat, exercises/practice/hello-world/hello-world.spec.js, exercises/practice/hello-world/hello-world.wat
Node 16 provides support for WebAssembly multi-value. This allows a function to return a N-way tuple. The JS API binds to this as an array of values.
This PR refactors the hello-world exercise to replace the C-style string with a "fat pointer" that returns the string length to the caller. I consider this a better approach that aligns with how WebAssembly will eventually handle "interface types" that will allow higher-level types like strings.
=> refactor: Use multi-value in hello-world

exercises/practice/grains/.meta/proof.ci.wat, exercises/practice/grains/grains.spec.js, exercises/practice/grains/grains.wat
Resolves #38 
I also changed the parameter `$squareNum` from an i64 to an i32 since it only has to express 1..64.
=> refactor: grains test cleanup

exercises/practice/bank-account/.meta/proof.ci.wat, exercises/practice/bank-account/bank-account.wat
I likely copied code and ended up with an unused parameter on the balance function. This PR removes this!
=> fix: bank-account delete unused parameter

exercises/practice/acronym/.docs/instructions.append.md, exercises/practice/all-your-base/.docs/instructions.append.md, exercises/practice/armstrong-numbers/.docs/instructions.append.md, exercises/practice/hamming/.docs/instructions.append.md
The documentation in shared/.docs/debug.md gets automatically appended to the instructions in the Web UI, so this information is redundant.
=> docs: Remove redundant debugging instructions

config.json, exercises/practice/rotational-cipher/.docs/instructions.append.md, exercises/practice/rotational-cipher/.docs/instructions.md, exercises/practice/rotational-cipher/.eslintrc, exercises/practice/rotational-cipher/.meta/config.json, exercises/practice/rotational-cipher/.meta/proof.ci.wat, exercises/practice/rotational-cipher/.meta/tests.toml, exercises/practice/rotational-cipher/.npmrc, exercises/practice/rotational-cipher/LICENSE, exercises/practice/rotational-cipher/babel.config.js, exercises/practice/rotational-cipher/package.json, exercises/practice/rotational-cipher/rotational-cipher.spec.js, exercises/practice/rotational-cipher/rotational-cipher.wat
rotational-cipher for [Nibbly November](https://forum.exercism.org/t/select-featured-exercises-for-nibbly-november/7604)
=> Add rotational-cipher exercise

exercises/practice/hello-world/.meta/instructions.append.md, exercises/practice/hello-world/hello-world.wat
Please see this [forum discussion](https://forum.exercism.org/t/hello-world-possible-issue-with-stub-code/7961) for details.
Added a comment to warn students that they need to adjust the export line in the stub file:
```webassembly
(func (export "hello") (result i32 i32)
(i32.const 64) (i32.const 14)
)
```
_"Goodby, Mars!"_ is `14`, but _"Hello, World!"_ is `13`, so if `(i32.const 14)` is not changed, the student won't pass the tests.
Also added a `caution` level instruction append to alert students.
Conversely, the stub can be altered so that it is already `13` -- but then it won't match "Goodby, Mars!".
=> [Hello World]:  Added comment to stub and Instruction Append

exercises/practice/all-your-base/.docs/instructions.append.md, exercises/practice/all-your-base/all-your-base.wat
Documentation-only change motivated by https://forum.exercism.org/t/regarding-the-input-to-all-your-base/8164.
=> docs: Clarify linear memory use in all-your-base

exercises/practice/grains/grains.wat
In the comments for the second function, the word "across" had an extra 's' at the end. Searched other files in exercise and didn't see any similar problem, just this file.
=> Update grains.wat - typo in "total" description

exercises/practice/all-your-base/all-your-base.spec.js
Resolves an error reported in https://forum.exercism.org/t/error-in-all-your-base-tests/8493 where the offset and length parameters were read by the test runner when the error code indicated they were invalid.
=> fix: all-your-base read offset / len if rc is 0

exercises/practice/acronym/.docs/instructions.append.md, exercises/practice/hamming/.docs/instructions.append.md, exercises/practice/resistor-color/.docs/instructions.append.md, exercises/practice/rna-transcription/.docs/instructions.append.md, exercises/practice/two-fer/.docs/instructions.append.md
Several problems use a range of memory offsets for a buffer.  The problem descriptions for some of these give an incorrect upper bound.  This change fixes them.  It was discussed in the forum in https://forum.exercism.org/t/minor-mistake-in-acronym-description/8492.
=> Several problems misstate the range of memory offsets used for buffers

config.json, exercises/practice/matching-brackets/.docs/instructions.append.md, exercises/practice/matching-brackets/.docs/instructions.md, exercises/practice/matching-brackets/.docs/introduction.md, exercises/practice/matching-brackets/.eslintrc, exercises/practice/matching-brackets/.meta/config.json, exercises/practice/matching-brackets/.meta/proof.ci.wat, exercises/practice/matching-brackets/.meta/tests.toml, exercises/practice/matching-brackets/.npmrc, exercises/practice/matching-brackets/LICENSE, exercises/practice/matching-brackets/babel.config.js, exercises/practice/matching-brackets/matching-brackets.spec.js, exercises/practice/matching-brackets/matching-brackets.wat, exercises/practice/matching-brackets/package-lock.json, exercises/practice/matching-brackets/package.json
(Also updated config.json to add references to exercise files)
This is one of the [48in24](https://forum.exercism.org/t/48in24-exercise-06-18-matching-brackets/11396) exercises.
=> Add matching brackets exercise

config.json, exercises/practice/run-length-encoding/.docs/instructions.append.md, exercises/practice/run-length-encoding/.docs/instructions.md, exercises/practice/run-length-encoding/.eslintrc, exercises/practice/run-length-encoding/.meta/config.json, exercises/practice/run-length-encoding/.meta/proof.ci.wat, exercises/practice/run-length-encoding/.meta/tests.toml, exercises/practice/run-length-encoding/.npmrc, exercises/practice/run-length-encoding/LICENSE, exercises/practice/run-length-encoding/babel.config.js, exercises/practice/run-length-encoding/package.json, exercises/practice/run-length-encoding/run-length-encoding.spec.js, exercises/practice/run-length-encoding/run-length-encoding.wat
Added new exercise for #48in24.
=> run-length-encoding-exercise: added new exercise.

exercises/practice/difference-of-squares/.docs/instructions.append.md, exercises/practice/leap/.docs/instructions.append.md, exercises/practice/matching-brackets/matching-brackets.spec.js, exercises/practice/matching-brackets/package.json, exercises/practice/sieve/package.json
=> package.json now references correct slug

config.json, exercises/practice/complex-numbers/.docs/instructions.append.md, exercises/practice/complex-numbers/.docs/instructions.md, exercises/practice/complex-numbers/.eslintrc, exercises/practice/complex-numbers/.meta/config.json, exercises/practice/complex-numbers/.meta/proof.ci.wat, exercises/practice/complex-numbers/.meta/tests.toml, exercises/practice/complex-numbers/.npmrc, exercises/practice/complex-numbers/LICENSE, exercises/practice/complex-numbers/babel.config.js, exercises/practice/complex-numbers/complex-numbers.spec.js, exercises/practice/complex-numbers/complex-numbers.wat, exercises/practice/complex-numbers/package.json
https://forum.exercism.org/t/new-exercise-complex-numbers/15845
=> new exercise: complex-numbers

config.json, exercises/practice/diamond/.docs/instructions.append.md, exercises/practice/diamond/.docs/instructions.md, exercises/practice/diamond/.eslintrc, exercises/practice/diamond/.meta/config.json, exercises/practice/diamond/.meta/proof.ci.wat, exercises/practice/diamond/.meta/tests.toml, exercises/practice/diamond/.npmrc, exercises/practice/diamond/LICENSE, exercises/practice/diamond/babel.config.js, exercises/practice/diamond/diamond.spec.js, exercises/practice/diamond/diamond.wat, exercises/practice/diamond/package.json
https://forum.exercism.org/t/new-exercise-diamond/15979
=> new exercise: diamond

exercises/practice/rational-numbers/.docs/instructions.append.md
=> Clarify logarithm discussion

exercises/practice/palindrome-products/package.json, exercises/practice/palindrome-products/palindrome-products.spec.js
=> palindrome-products: fix spec

config.json, exercises/practice/meetup/.docs/instructions.md, exercises/practice/meetup/.docs/introduction.md, exercises/practice/meetup/.eslintrc, exercises/practice/meetup/.meta/config.json, exercises/practice/meetup/.meta/proof.ci.wat, exercises/practice/meetup/.meta/tests.toml, exercises/practice/meetup/.npmrc, exercises/practice/meetup/LICENSE, exercises/practice/meetup/babel.config.js, exercises/practice/meetup/meetup.spec.js, exercises/practice/meetup/meetup.wat, exercises/practice/meetup/package.json
I am still undecided if we should pre-define the pseudo-enums for weekdays and weeks, but I found the exercise already hard enough due to the lack of a standard library handling the peculiarities of the gregorian calendar. What's your opinion on this one?
=> new exercise: meetup

exercises/practice/grade-school/grade-school.spec.js, exercises/practice/grade-school/package.json
Unfortunately, we have the escore installation issue again. To counter this, I removed arrays from the tests completely and test the actual output (which is preferable in any case).
=> grade-school: tests without array

config.json, exercises/practice/piecing-it-together/.docs/instructions.md, exercises/practice/piecing-it-together/.docs/introduction.md, exercises/practice/piecing-it-together/.eslintrc, exercises/practice/piecing-it-together/.meta/config.json, exercises/practice/piecing-it-together/.meta/proof.ci.wat, exercises/practice/piecing-it-together/.meta/tests.toml, exercises/practice/piecing-it-together/.npmrc, exercises/practice/piecing-it-together/LICENSE, exercises/practice/piecing-it-together/babel.config.js, exercises/practice/piecing-it-together/package.json, exercises/practice/piecing-it-together/piecing-it-together.spec.js, exercises/practice/piecing-it-together/piecing-it-together.wat
After getting my first problem description merged, I knew I wanted to solve this in web assembly. So while I am at it, I can just create this exercise. I considered using the memory to convey the different values, but the mix of i32 and f64 made this unneccessarily cumbersome.
=> new exercise: piecing it together
