exercism/wasm

config.json
exercises/practice/reverse-string/.docs/instructions.md
exercises/practice/reverse-string/.eslintrc
exercises/practice/reverse-string/.meta/config.json
exercises/practice/reverse-string/.meta/proof.ci.wat
exercises/practice/reverse-string/.meta/tests.toml
exercises/practice/reverse-string/.npmrc
exercises/practice/reverse-string/LICENSE
exercises/practice/reverse-string/babel.config.js
exercises/practice/reverse-string/compile-wat.js
exercises/practice/reverse-string/package.json
exercises/practice/reverse-string/reverse-string.spec.js
exercises/practice/reverse-string/reverse-string.wat

Now that I figured out how multi-value returns work with JavaScript interop, I feel more comfortable porting over string processing problems. See the JS wrapper function in the spec for an example of how UTF8 encoding and decoding works.

feat: practice exercise reverse-string

---

config.json
exercises/practice/resistor-color/.docs/instructions.append.md
exercises/practice/resistor-color/.docs/instructions.md
exercises/practice/resistor-color/.eslintrc
exercises/practice/resistor-color/.meta/config.json
exercises/practice/resistor-color/.meta/proof.ci.wat
exercises/practice/resistor-color/.meta/tests.toml
exercises/practice/resistor-color/.npmrc
exercises/practice/resistor-color/LICENSE
exercises/practice/resistor-color/babel.config.js
exercises/practice/resistor-color/compile-wat.js
exercises/practice/resistor-color/package.json
exercises/practice/resistor-color/resistor-color.spec.js
exercises/practice/resistor-color/resistor-color.wat

This is a good example of how the string and array examples can get pretty complicated! I would expect this to be similar in all of the assembly languages.

feat: Resistor color

---

exercises/practice/acronym/.meta/config.json
exercises/practice/all-your-base/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/bank-account/.meta/config.json
exercises/practice/binary-search/.meta/config.json
exercises/practice/circular-buffer/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/resistor-color/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/triangle/.meta/config.json

This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.

Reformat exercise config files

---

config.json

I've created a simple version of the representer that "just" normalizes the submitted code: https://github.com/exercism/wasm-representer/pull/4

Enable representer

---

exercises/practice/acronym/.meta/config.json
exercises/practice/all-your-base/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/bank-account/.meta/config.json
exercises/practice/binary-search/.meta/config.json
exercises/practice/circular-buffer/.meta/config.json
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/darts/.meta/config.json
exercises/practice/difference-of-squares/.meta/config.json
exercises/practice/grains/.meta/config.json
exercises/practice/hamming/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/nucleotide-count/.meta/config.json
exercises/practice/pangram/.meta/config.json
exercises/practice/pop-count/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/resistor-color/.meta/config.json
exercises/practice/reverse-string/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/rotational-cipher/.meta/config.json
exercises/practice/square-root/.meta/config.json
exercises/practice/triangle/.meta/config.json
exercises/practice/two-fer/.meta/config.json

Follow up PR as requested in https://github.com/exercism/wasm/pull/87#issuecomment-1811932267.

chore: Add package.json as invalidator file

---

config.json
exercises/practice/knapsack/.docs/instructions.append.md
exercises/practice/knapsack/.docs/instructions.md
exercises/practice/knapsack/.docs/introduction.md
exercises/practice/knapsack/.eslintrc
exercises/practice/knapsack/.meta/config.json
exercises/practice/knapsack/.meta/proof.ci.wat
exercises/practice/knapsack/.meta/tests.toml
exercises/practice/knapsack/.npmrc
exercises/practice/knapsack/LICENSE
exercises/practice/knapsack/babel.config.js
exercises/practice/knapsack/knapsack.spec.js
exercises/practice/knapsack/knapsack.wat
exercises/practice/knapsack/package-lock.json
exercises/practice/knapsack/package.json

This is one of the 48in24 exercises.

Add Knapsack exercise

---

exercises/practice/nucleotide-count/nucleotide-count.spec.js

nucleotide-count uses xtest

---

exercises/practice/matching-brackets/matching-brackets.wat
exercises/practice/nucleotide-count/nucleotide-count.spec.js
exercises/practice/reverse-string/reverse-string.spec.js
exercises/practice/rna-transcription/rna-transcription.spec.js
exercises/practice/rotational-cipher/rotational-cipher.spec.js
exercises/practice/run-length-encoding/run-length-encoding.spec.js
exercises/practice/two-fer/two-fer.spec.js

Tests use inputLengthEncoded

---

exercises/practice/phone-number/phone-number.wat

Stub for phone-number exercise

---

config.json
exercises/practice/robot-simulator/.docs/instructions.append.md
exercises/practice/robot-simulator/.docs/instructions.md
exercises/practice/robot-simulator/.eslintrc
exercises/practice/robot-simulator/.meta/config.json
exercises/practice/robot-simulator/.meta/proof.ci.wat
exercises/practice/robot-simulator/.meta/tests.toml
exercises/practice/robot-simulator/.npmrc
exercises/practice/robot-simulator/LICENSE
exercises/practice/robot-simulator/babel.config.js
exercises/practice/robot-simulator/package-lock.json
exercises/practice/robot-simulator/package.json
exercises/practice/robot-simulator/robot-simulator.spec.js
exercises/practice/robot-simulator/robot-simulator.wat

See https://forum.exercism.org/t/add-robot-simulator-exercise/15708

new exercise: robot simulator

---

config.json
exercises/practice/queen-attack/.docs/instructions.append.md
exercises/practice/queen-attack/.docs/instructions.md
exercises/practice/queen-attack/.eslintrc
exercises/practice/queen-attack/.meta/config.json
exercises/practice/queen-attack/.meta/proof.ci.wat
exercises/practice/queen-attack/.meta/tests.toml
exercises/practice/queen-attack/.npmrc
exercises/practice/queen-attack/LICENSE
exercises/practice/queen-attack/babel.config.js
exercises/practice/queen-attack/package-lock.json
exercises/practice/queen-attack/package.json
exercises/practice/queen-attack/queen-attack.spec.js
exercises/practice/queen-attack/queen-attack.wat

See https://forum.exercism.org/t/add-queen-attack-exercise/15713

new exercise: queen-attack

---

config.json
exercises/practice/ocr-numbers/.docs/instructions.append.md
exercises/practice/ocr-numbers/.docs/instructions.md
exercises/practice/ocr-numbers/.eslintrc
exercises/practice/ocr-numbers/.meta/config.json
exercises/practice/ocr-numbers/.meta/proof.ci.wat
exercises/practice/ocr-numbers/.meta/tests.toml
exercises/practice/ocr-numbers/.npmrc
exercises/practice/ocr-numbers/LICENSE
exercises/practice/ocr-numbers/babel.config.js
exercises/practice/ocr-numbers/ocr-numbers.spec.js
exercises/practice/ocr-numbers/ocr-numbers.wat
exercises/practice/ocr-numbers/package-lock.json
exercises/practice/ocr-numbers/package.json

https://forum.exercism.org/t/which-exercise-should-i-do-next/15769/3

new exercise: ocr-numbers

---

config.json
exercises/practice/resistor-color-trio/.docs/instructions.append.md
exercises/practice/resistor-color-trio/.docs/instructions.md
exercises/practice/resistor-color-trio/.eslintrc
exercises/practice/resistor-color-trio/.meta/config.json
exercises/practice/resistor-color-trio/.meta/proof.ci.wat
exercises/practice/resistor-color-trio/.meta/tests.toml
exercises/practice/resistor-color-trio/.npmrc
exercises/practice/resistor-color-trio/LICENSE
exercises/practice/resistor-color-trio/babel.config.js
exercises/practice/resistor-color-trio/package-lock.json
exercises/practice/resistor-color-trio/package.json
exercises/practice/resistor-color-trio/resistor-color-trio.spec.js
exercises/practice/resistor-color-trio/resistor-color-trio.wat

https://forum.exercism.org/t/new-exercise-resistor-color-trio/15857

new exercise: resistor-color-trio

---

config.json
exercises/practice/space-age/.docs/instructions.append.md
exercises/practice/space-age/.docs/instructions.md
exercises/practice/space-age/.docs/introduction.md
exercises/practice/space-age/.eslintrc
exercises/practice/space-age/.meta/config.json
exercises/practice/space-age/.meta/proof.ci.wat
exercises/practice/space-age/.meta/tests.toml
exercises/practice/space-age/.npmrc
exercises/practice/space-age/LICENSE
exercises/practice/space-age/babel.config.js
exercises/practice/space-age/package.json
exercises/practice/space-age/space-age.spec.js
exercises/practice/space-age/space-age.wat

https://forum.exercism.org/t/new-exercise-space-age/15869

new exercise: space-age

---

config.json
exercises/practice/pig-latin/.docs/instructions.append.md
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/pig-latin/.docs/introduction.md
exercises/practice/pig-latin/.eslintrc
exercises/practice/pig-latin/.meta/config.json
exercises/practice/pig-latin/.meta/proof.ci.wat
exercises/practice/pig-latin/.meta/tests.toml
exercises/practice/pig-latin/.npmrc
exercises/practice/pig-latin/LICENSE
exercises/practice/pig-latin/babel.config.js
exercises/practice/pig-latin/package.json
exercises/practice/pig-latin/pig-latin.spec.js
exercises/practice/pig-latin/pig-latin.wat

https://forum.exercism.org/t/new-exercise-pig-latin/15900

new exercise: pig-latin

---

exercises/practice/reverse-string/.meta/tests.toml

reverse-string: exclude wide character tests

---

config.json
exercises/practice/affine-cipher/.docs/instructions.append.md
exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/affine-cipher/.eslintrc
exercises/practice/affine-cipher/.meta/config.json
exercises/practice/affine-cipher/.meta/proof.ci.wat
exercises/practice/affine-cipher/.meta/tests.toml
exercises/practice/affine-cipher/.npmrc
exercises/practice/affine-cipher/LICENSE
exercises/practice/affine-cipher/affine-cipher.spec.js
exercises/practice/affine-cipher/affine-cipher.wat
exercises/practice/affine-cipher/babel.config.js
exercises/practice/affine-cipher/package.json

https://forum.exercism.org/t/new-exercise-affine-cipher/15932

new exercise: affine-cipher

---

config.json
exercises/practice/rectangles/.docs/instructions.append.md
exercises/practice/rectangles/.docs/instructions.md
exercises/practice/rectangles/.eslintrc
exercises/practice/rectangles/.meta/config.json
exercises/practice/rectangles/.meta/proof.ci.wat
exercises/practice/rectangles/.meta/tests.toml
exercises/practice/rectangles/.npmrc
exercises/practice/rectangles/LICENSE
exercises/practice/rectangles/babel.config.js
exercises/practice/rectangles/package.json
exercises/practice/rectangles/rectangles.spec.js
exercises/practice/rectangles/rectangles.wat

https://forum.exercism.org/t/new-exercise-rectangles/15990

new exercise: rectangles

---

config.json
exercises/practice/sublist/.docs/instructions.append.md
exercises/practice/sublist/.docs/instructions.md
exercises/practice/sublist/.eslintrc
exercises/practice/sublist/.meta/config.json
exercises/practice/sublist/.meta/proof.ci.wat
exercises/practice/sublist/.meta/tests.toml
exercises/practice/sublist/.npmrc
exercises/practice/sublist/LICENSE
exercises/practice/sublist/babel.config.js
exercises/practice/sublist/package.json
exercises/practice/sublist/sublist.spec.js
exercises/practice/sublist/sublist.wat

https://forum.exercism.org/t/new-exercise-sublist/16150

new exercise: sublist

---

config.json

Exercises now have their canonical names from
problem-specifications metadata.toml

Sort exercises by difficulty, slug

---

exercises/practice/bowling/package.json
exercises/practice/pangram/package.json
exercises/practice/queen-attack/package.json

Correct package.json

---

exercises/practice/pascals-triangle/package.json
exercises/practice/pascals-triangle/pascals-triangle.spec.js
exercises/practice/protein-translation/protein-translation.spec.js

Remove console.log

---

config.json
exercises/practice/grade-school/.docs/instructions.append.md
exercises/practice/grade-school/.docs/instructions.md
exercises/practice/grade-school/.eslintrc
exercises/practice/grade-school/.meta/config.json
exercises/practice/grade-school/.meta/proof.ci.wat
exercises/practice/grade-school/.meta/tests.toml
exercises/practice/grade-school/.npmrc
exercises/practice/grade-school/LICENSE
exercises/practice/grade-school/babel.config.js
exercises/practice/grade-school/grade-school.spec.js
exercises/practice/grade-school/grade-school.wat
exercises/practice/grade-school/package.json

new exercise: grade-school

---

config.json
exercises/practice/nth-prime/.docs/instructions.md
exercises/practice/nth-prime/.eslintrc
exercises/practice/nth-prime/.meta/config.json
exercises/practice/nth-prime/.meta/proof.ci.wat
exercises/practice/nth-prime/.meta/tests.toml
exercises/practice/nth-prime/.npmrc
exercises/practice/nth-prime/LICENSE
exercises/practice/nth-prime/babel.config.js
exercises/practice/nth-prime/nth-prime.spec.js
exercises/practice/nth-prime/nth-prime.wat
exercises/practice/nth-prime/package.json

I left out the "there is no nth prime" error, since we would have to handle the error on the JS side anyways, so there is little value to that part - and it is not tested in arm64 assembly, too.

new exercise: nth-prime

---

exercises/practice/eliuds-eggs/.docs/introduction.md
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/luhn/.docs/instructions.md
exercises/practice/luhn/.docs/introduction.md
exercises/practice/meetup/.docs/instructions.md
exercises/practice/phone-number/.docs/instructions.md

Sync exercise instructions
